### PR TITLE
added code of conduct

### PR DESCRIPTION
**Pull request by Mohit-Aasirwal**
I've added code of conduct for this repository.
Kindly merge it with issuing label hacktoberfest.

### CODE REVIEW

**Comment by Mohit-Aasirwal** [comment]
Also add hacktoberfest label to your repository and hacktoberfest-accepted label to this PR also please

**Comment by AyushSarode** [comment]
Rename it as CODE OF CONDUCT.md

**Comment by Mohit-Aasirwal** [comment]
I've renamed the file but does not removed the existing one.
kindly merge the PR and do it by yourself.

**Review by AyushSarode — APPROVED** [review]
Good Work

**Pull request merged**
