### PR TITLE
Added Icons to the Buttons

### PR DESCRIPTION
**Pull request by abhijeetanand29**

### CODE REVIEW

**Comment by AyushSarode** [comment]
Its not working correctly. When I hover on any of those icon it should display as it is.
Screenshot (583)

**Comment by AyushSarode** [comment]
> Its not working correctly. When I hover on any of those icon it should display as it is.
Also add icon pattern like this - https://cdn.shopify.com/s/files/1/1431/5776/products/instagram-round-logo-rubber-stamp.png?v=1507308608


 Screenshot (583)

**Comment by abhijeetanand29** [comment]
On it

**Comment by abhijeetanand29** [comment]
I have committed all the rquired changes.

**Comment by AyushSarode** [comment]
> I have committed all the required changes.
> 
> Also it is showing in my hacktoberfest dashboard that this issue is not participating, can you look into it?

Great Work! keep it up.
I just labeled this issue. Don't worry about that.

**Pull request merged**
